### ISSUE TITLE
Nameclash for antd Row

### ISSUE THREAD

**Issue by an-tex** [ScalablyTyped/Converter#189] opened 2020-08-03 13:35 UTC
Starting with antd 4.4.x (tested with latest 4.5.2) there are two components ending up under the same name `Row`:

picked:
https://github.com/ant-design/ant-design/blob/master/components/descriptions/Row.tsx

and lost:
https://github.com/ant-design/ant-design/blob/master/components/grid/row.tsx

I wonder how it isn't clashing within TS. Or It should the first one not be exported at all as it's only used internally and not (re)exported by the https://github.com/ant-design/ant-design/blob/master/components/descriptions/index.tsx ?

Here's the diff that leads to the regression since 4.3.x https://github.com/ant-design/ant-design/commit/a3f1de32932b00d31637264f6746157ad4c2786d#diff-5906235ee86452c86a05432902ffa40f

**Comment by oyvindberg** [comment] 2020-08-03 23:31
Thanks for the report.

It's by design that in the case of name collision one has to be picked. I'm not sure that it's optimal this way, butpart of the point of a `components` package was that it would simplify everything by being flat, and I thought it wouldnt come up much.
The problem here is that the wrong component is picked.

The can heuristic for which component to choose be seen [here](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/flavours/IdentifyReactComponents.scala#L11). I'm adjusting it now in #190 to prioritize shorter imports even more, so that the correct `Row` wins.

**Comment by an-tex** [comment] 2020-08-04 07:09
Thanks for giving directions about how the heuristics work. I'll try to get more into the converter internals to gain a better understanding. And thanks for changing the prioritization, that grid/Row component is quiet important ;)

Still, I wonder why this collision happens at all. Especially why is there meant to be a https://github.com/ant-design/ant-design/blob/master/components/descriptions/Row.tsx component in the first place? It's module entry point https://github.com/ant-design/ant-design/blob/master/components/descriptions/index.tsx does not re-export the Row module. Hence the converter shouldn't be exporting that descriptions/Row as a component at all as it's just for "internal use" ?

**Comment by oyvindberg** [comment] 2020-08-04 07:39
The code collects *all* components which are reachable, and that other row is reachable through `require("antd/components/descriptions/Row").default` (or something like that).

The next step is that the components are grouped by name, and one component is chosen per name to present a flat namespace. The code I linked to in this case gave too much importance to the export being called `default`

**Comment by an-tex** [comment] 2020-08-04 08:33
To me it seems there is a difference in scope between components which are:
- "directly" exported through index.tsx, thats for ant pretty much only the ones in https://github.com/ant-design/ant-design/blob/master/components/index.tsx (same for mui at https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/index.d.ts )
- "inderectly" exported through import chains (e.g https://github.com/ant-design/ant-design/blob/master/components/descriptions/Row.tsx )

When using TS, for the first case you can just write `import { Row } from 'antd';` to get the grid/Row. To import the descriptions/Row you'd need to write `import { Row } from 'antd/lib/descriptions/Row';`

So I wonder whether we should follow the same scoping principle. Having a flat namespace (directly under .components package) only for the directly exported components (first case), and a more hierarchical namespace (sub packages?) for the indirectly exported ones (second case).

The grid/Row component would end up at `typings.antd.components.Row`, and the descriptions/Row e.g. at `typings.antd.components.descriptions.Row`.

This way we'd have the "important"/non-internal/most used components directly available in a flat namespace. The other rather internal components would still be accessible, but in a more scoped manner. Just like in TS. This should avoid any nameclashes and make picking heuristics unnecessary?

**Comment by oyvindberg** [comment] 2020-08-04 17:27
Yeah, that's very good input @an-tex . I've certainly thought about it, and it's a pretty good idea.

I'm a bit hesitant to go in that direction:
- with #190 merged, all the top level (`import { Row } from 'antd';`) components will always be available
- My hypothesis is that it's *very* rare for a library to have two different and useful components with the same name (except say `List.Item` and `Menu.Item` which would be ok because they are nested). 
- A given component may be exported arbitrary many times through different module paths, and I really want to avoid having to choose between say four different `FooComponent`s each time 
- Doubling or tripling the number of components we generate will make compilation time worse (even though the worst of it is taken care of with the shared builders)

I'd say let's go ahead with the new heuristics and see if any more problems show up first, WDYT?

**Closed** 2020-08-04 18:25 UTC

**Comment by an-tex** [comment] 2020-08-05 07:09
> * with #190 merged, all the top level (`import { Row } from 'antd';`) components will always be available

Thanks for clarifying! That point in mind your proposal sounds very reasonable :) I guess those things mainly happen with those crazy huge libraries like ant/mui etc and once we have the test coverage there e.g. by having demos for more components, all should be fine. Thanks!
