### ISSUE TITLE
Compiled with sbt 1.4.0 line?

### ISSUE THREAD

**Issue by ngbinh** [ScalablyTyped/Converter#168] opened 2020-06-17 08:52 UTC
I tried to use `sbt-coverter` with sbt `1.4.0-M1` and it seems to have problem with classpath:

```
webChart/compile
[info] Total time: 1 sec
[error] stack trace is suppressed; run last webChart / stInternalZincCompiler for the full output
[error] (webChart / stInternalZincCompiler) java.lang.NoSuchMethodError: xsbti.compile.CompileOptions.withClasspath([Ljava/io/File;)Lxsbti/compile/CompileOptions;
[error] Total time: 1 s, completed Jun 17, 2020, 3:51:23 PM
sbt:Anduin Design> 

```

I have tried to update sbt myself for `sbt-converter` but getting into the internal `ZincCompiler` looks a bit harder than I thought.

**Comment by oyvindberg** [comment] 2020-06-17 09:25
That milestone is not binary compatible with sbt 1.3 apparently. I think the only useful thing we can do is to let them know it's not compatible, although I would be very surprised if they don't have a plan for this :)

**Comment by dwijnand** [comment] 2020-09-07 14:26
This should be fixed, but could someone confirm?  1.4.0-RC1 is out (and has a 14 day regression-reporting window).

**Comment by ngbinh** [comment] 2020-09-07 15:00
I can try it out sometime this week and report back here

**Comment by ngbinh** [comment] 2020-09-07 15:33
Hmm, I am seeing this on my local build. Probably something else

```
[info] resolving key references (34157 settings) ...
[error] java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
[error]         at org.scalablytyped.converter.internal.scalajs.TypeRef$.<init>(tree.scala:503)
[error]         at org.scalablytyped.converter.internal.scalajs.TypeRef$.<clinit>(tree.scala)
[error]         at org.scalablytyped.converter.internal.scalajs.flavours.JapgollyTypeConversions$.apply(JapgollyTypeConversions.scala:19)
[error]         at org.scalablytyped.converter.internal.scalajs.flavours.JapgollyFlavour.<init>(JapgollyFlavour.scala:11)
[error]         at org.scalablytyped.converter.internal.importer.ConversionOptions.<init>(ConversionOptions.scala:31)
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedPluginBase$.$anonfun$projectSettings$13(ScalablyTypedPluginBase.scala:101)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: scala.math.Ordering$$anon$7
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error]         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error]         at org.scalablytyped.converter.internal.scalajs.TypeRef$.<init>(tree.scala:503)
[error]         at org.scalablytyped.converter.internal.scalajs.TypeRef$.<clinit>(tree.scala)
[error]         at org.scalablytyped.converter.internal.scalajs.flavours.JapgollyTypeConversions$.apply(JapgollyTypeConversions.scala:19)
[error]         at org.scalablytyped.converter.internal.scalajs.flavours.JapgollyFlavour.<init>(JapgollyFlavour.scala:11)
[error]         at org.scalablytyped.converter.internal.importer.ConversionOptions.<init>(ConversionOptions.scala:31)
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedPluginBase$.$anonfun$projectSettings$13(ScalablyTypedPluginBase.scala:101)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.EvaluateSettings$MixedNode.evaluate0(INode.scala:228)
[error]         at sbt.internal.util.EvaluateSettings$INode.evaluate(INode.scala:170)
[error]         at sbt.internal.util.EvaluateSettings.$anonfun$submitEvaluate$1(INode.scala:87)
[error]         at sbt.internal.util.EvaluateSettings.sbt$internal$util$EvaluateSettings$$run0(INode.scala:99)
[error]         at sbt.internal.util.EvaluateSettings$$anon$3.run(INode.scala:94)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
```

**Comment by ngbinh** [comment] 2020-09-07 15:40
Setting `scalaVersion` to `2.12.11` likes the one used in `sbt-converter` help me get pass the previous error but I get this one when trying to invoke a function in `sbt-converter`

```scala
last webTable / stImport                                                                                                                                              
[warn] ImportTypingsGenSources.scala:55 Importing tabulator-tables [project => web-table, ms => 12658]                                                                                   
[error] java.lang.NoSuchMethodError: scala.collection.immutable.List.$anonfun$flatMap$1$adapted(Lscala/runtime/BooleanRef;Lscala/runtime/ObjectRef;Lscala/runtime/ObjectRef;Ljava/lang/Ob
ject;)Ljava/lang/Object;                                                                                                                                                                 
[error]         at org.scalablytyped.converter.internal.ts.ModuleNameParser$.apply(ModuleNameParser.scala:9)                                                                             
[error]         at org.scalablytyped.converter.internal.importer.LibraryResolver$.moduleNameFor(LibraryResolver.scala:81)                                                                
[error]         at org.scalablytyped.converter.internal.importer.Source$.helperFile(Source.scala:60)                                                                                     
[error]         at org.scalablytyped.converter.internal.importer.PathsFromTsLibSource$.$anonfun$apply$3(PathsFromTsLibSource.scala:22)                                                   
[error]         at org.scalablytyped.converter.internal.importer.PathsFromTsLibSource$.apply(PathsFromTsLibSource.scala:22)                                                              
[error]         at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.apply(Phase1ReadTypescript.scala:126)
[error]         at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.apply(Phase1ReadTypescript.scala:21)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$4(PhaseRunner.scala:71)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$3(PhaseRunner.scala:71)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRes.flatMap(PhaseRes.scala:26)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRes.flatMap$(PhaseRes.scala:24)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRes$Ok.flatMap(PhaseRes.scala:33)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:70)
[error]         at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:47)
[error]         at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:47)
[error]         at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error]         at org.scalablytyped.converter.internal.phases.PhaseRunner$.apply(PhaseRunner.scala:47)
[error]         at org.scalablytyped.converter.internal.ImportTypingsGenSources$.$anonfun$apply$7(ImportTypingsGenSources.scala:85)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:943)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:285)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error]         at org.scalablytyped.converter.internal.ImportTypingsGenSources$.apply(ImportTypingsGenSources.scala:85)
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedConverterGenSourcePlugin$.$anonfun$projectSettings$7(ScalablyTypedConverterGenSourcePlugin.scala:116)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:233)

```

**Comment by nafg** [comment] 2020-09-07 16:36
A mismatched Scala binary version is very odd but I don't see how it could be related to the original issue

**Comment by oyvindberg** [comment] 2020-09-07 17:17
Thanks for reaching out @dwijnand . 

Just as a quick background, this sbt plugin uses sbt in an unusual manner. It needs a compiler before `libraryDependencies` is computed. For that reason it downloads a scala compiler through coursier and sets it up with zinc. Details are in [ZincCompiler.scala](https://github.com/ScalablyTyped/Converter/blob/master/sbt-converter/src/main/scala/org/scalablytyped/converter/internal/ZincCompiler.scala). You'll notice it even touches the `internal` namespace of sbt, so I'm not completely shocked to be seeing problems. Also I should note that I hope to improve the design, I just don't have any ideas how.

My expectation was that usage of internal types could potentially limit the plugin to a given minor version of sbt. OTOH I expected `xsbti` to be stable since somebody went to the trouble of defining interfaces in java.

## Ways forward:

1) I update the plugin and require sbt 1.4.x from the next release. Case closed here, I would be fine with it.
2) If you consider it bad enough to break `CompileOptions.withClasspath` (and perhaps more) since it might cause breakage elsewhere I'd be happy to work with you through an RC2 and figure out what more changed API is depended upon here as well as test changes.

WDYT @dwijnand ?

**Comment by oyvindberg** [comment] 2020-09-07 17:17
Is that a patched version you're using @ngbinh ? Because I just tested the newest release version against sbt 1.4.0-RC1 and got the same error as in the original post.

If it is feel free to open a draft PR :+1:

**Comment by nafg** [comment] 2020-09-07 19:16
Perhaps if you need to do it that way, it would be best to contribute a
high-level API to SBT that generalizes the concept of dynamically generated
libraries, or something somewhat more low level, but it should be made part
of SBT's API. That way SBT's internals can be refactored without silently
breaking external plugins.

If you do need to publish a version for different minor SBT versions, then
instead of telling people to write addSbtPlugin and a different thing to
write depending on their build.properties or installed SBT versions,
perhaps you could work out something they can paste into plugins.sbt that
automatically determines the right thing to do.


If you want to do something less radical relative to SBT, it might be
somewhat more work for users, but you might create an intermediate
subproject that represents the generated facades instead of trying to do it
within one subproject. It might be possible to generate the subproject
synthetically in which case it might not be more work.

**Comment by dwijnand** [comment] 2020-09-07 19:18
> My expectation was that usage of internal types could potentially limit the plugin to a given minor version of sbt. OTOH I expected `xsbti` to be stable since somebody went to the trouble of defining interfaces in java.

Those are to bridge data from the scala version used throughout zinc/sbt (the "host" scala version, i.e. 2.12 these days) to the target scala version (e.g. 2.13).

> * I update the plugin and require sbt 1.4.x from the next release. Case closed here, I would be fine with it.

That sounds good to me - but I'm probably acting biased to the fact that I hadn't heard of ScalablyTyped till nafg brought it up today.

**Comment by oyvindberg** [comment] 2020-09-07 19:43
thanks for the input @nafg :+1: 

> Perhaps if you need to do it that way, it would be best to contribute a
high-level API to SBT that generalizes the concept of dynamically generated
libraries, or something somewhat more low level, but it should be made part
of SBT's API. That way SBT's internals can be refactored without silently
breaking external plugins.

I'd love to, but the design space for that is... huge. In this plugin the need is really just an instance of the Scala compiler.

> If you do need to publish a version for different minor SBT versions, then
instead of telling people to write addSbtPlugin and a different thing to
write depending on their build.properties or installed SBT versions,
perhaps you could work out something they can paste into plugins.sbt that
automatically determines the right thing to do.

What I did was essentially to inline just enough of sbt code to get a working compiler and tweak it slightly.
The current code worked fine throughout 1.3.x without any changes, so I haven't had a reason to revisit it.

> If you want to do something less radical relative to SBT, it might be
somewhat more work for users, but you might create an intermediate
subproject that represents the generated facades instead of trying to do it
within one subproject. It might be possible to generate the subproject
synthetically in which case it might not be more work.

This is more or less what the [source generator plugin](https://scalablytyped.org/docs/library-developer) does (if I understand you correctly, that is).
Among other issues it means all the generated code will have to be recompiled every time you run `clean`, which I think is too slow to deal with.

**Comment by oyvindberg** [comment] 2020-09-07 20:00
> Those are to bridge data from the scala version used throughout zinc/sbt (the "host" scala version, i.e. 2.12 these days) to the target scala version (e.g. 2.13).

Yeah, I guess I read too much into it. 
 
> That sounds good to me - but I'm probably acting biased to the fact that I hadn't heard of ScalablyTyped till nafg brought it up today.

Yeah, don't worry - I'm trying to stabilize it before promoting it too much :)

Pushed a fix in #199 (cc @ngbinh )

**Comment by nafg** [comment] 2020-09-07 21:04
> That sounds good to me - but I'm probably acting biased to the fact that I hadn't heard of ScalablyTyped till nafg brought it up today.

@dwijnand it's a complete revolution in scala.js development and its ecosystem ;)


> I'd love to, but the design space for that is... huge. In this plugin the need is really just an instance of the Scala compiler.

@oyvindberg 
Then occam's razor would suggest to design it with only your use case in mind. More general APIs could always be added later if the need would arise.

**Comment by oyvindberg** [comment] 2020-09-26 21:29
Bumped to RC2. I discovered why you saw those `ClassNotFoundException` @ngbinh , I had misconfigured the optimizer to inline from all packages instead of only the `internal` package, so the plugin could in theory break after  changes in any dependencies in sbt, and sbt bumped the scala version. *cough* It'll be fixed now anyway :)

**Comment by ngbinh** [comment] 2020-09-27 01:23
Thanks

**Comment by dispalt** [comment] 2020-09-27 01:24
Just tested it on a large codebase w/ 1.4.0-RC2 and it works well.

**Closed** 2020-10-04 23:06 UTC
